#!/bin/sh -l
# FILENAME:  runjob

#SBATCH -A daminton
#SBATCH --nodes=1 
#SBATCH --time=100:00:00
#SBATCH --job-name test


source /etc/profile
module load intel
module load idl
cd $SLURM_SUBMIT_DIR

idl < start.in
