AC_INIT([Cratered Terrain Evolution Model], [1.1],
		  [David Minton <daminton@purdue.edu> , James Richardson <jerichardsonjr@me.com>],
		  [CTEM])
FCFLAGS=""
AC_CONFIG_AUX_DIR([config])
AC_CONFIG_SRCDIR([src/main/CTEM.f90])
AM_INIT_AUTOMAKE([subdir-objects])
AC_LANG([Fortran])
AC_PROG_FC([ifort gfortran])
AC_FC_FREEFORM
AC_PROG_INSTALL
AC_OUTPUT([Makefile src/Makefile])
