"""
This is an example of a standalone script. Files must be generated by a preprocessing script (this is an atypical useage
and is only here for testing purposes).
"""
import ctem
sim = ctem.Simulation(isnew=False)
sim.compute_one_interval()