import numpy as np
import os
import subprocess
import shutil
from ctem import util
import sys
import pandas
from ctem import craterproduction
from scipy.interpolate import interp1d

class Simulation:
    """
    This is a class that defines the basic CTEM simulation object. It initializes a dictionary of user and reads
    it in from a file (default name is ctem.in). It also creates the directory structure needed to store simulation
    files if necessary.
    """
    def __init__(self, param_file="ctem.in", isnew=True):
        currentdir = os.getcwd()
        self.user = {
            'restart': None,
            'runtype': None,
            'popupconsole': None,
            'saveshaded': None,
            'saverego': None,
            'savetruelist': None,
            'seedn': 1,
            'totalimpacts': 0,
            'ncount': 0,
            'curyear': 0.0,
            'fracdone': 1.0,
            'masstot': 0.0,
            'interval': 0.0,
            'numintervals': 0,
            'pix': -1.0,
            'gridsize': -1,
            'seed': 0,
            'maxcrat': 1.0,
            'shadedminhdefault': 1,
            'shadedmaxhdefault': 1,
            'shadedminh': 0.0,
            'shadedmaxh': 0.0,
            'workingdir': currentdir,
            'ctemfile': os.path.join(currentdir, param_file),
            'impfile': None,
            'sfdcompare': None,
            'sfdfile': None,
            'quasimc': None,
            'realcraterlist': None,
        }

        self.user = util.read_user_input(self.user)
       
        # This is containsall files generated by the main Fortran CTEM program plus the ctem.dat file that
        # communicates the state of the simulation from the Python driver to the Fortran program
        self.output_filenames = {
            'dat': 'ctem.dat',
            'dem': 'surface_dem.dat',
            'diam': 'surface_diam.dat',
            'ejc': 'surface_ejc.dat',
            'pos': 'surface_pos.dat',
            'time': 'surface_time.dat',
            'ocum': 'ocumulative.dat',
            'odist': 'odistribution.dat',
            'pdist': 'pdistribution.dat',
            'tcum' : 'tcumulative.dat',
            'tdist' : 'tdistribution.dat',
            'impmass' : 'impactmass.dat',
            'fracdone' : 'fracdone.dat',
            'regodepth' : 'regolithdepth.dat',
            'ejmax' : 'ejecta_table_max.dat',
            'ejmin' : 'ejecta_table_min.dat',
            'testprof' : 'testprofile.dat',
            'craterscale' : 'craterscale.dat',
            'craterlist' : 'craterlist.dat'
        }

        for k, v in self.output_filenames.items():
            self.output_filenames[k] = os.path.join(currentdir, v)

        self.directories = ['dist', 'misc', 'surf']
        if self.user['saveshaded'].upper() == 'T':
            self.directories.append('shaded')
        if self.user['saverego'].upper() == 'T':
            self.directories.append('rego')
            
        # Set up data arrays
        self.seedarr = np.zeros(100, dtype=int)
        self.seedarr[0] = self.user['seed']
        self.odist = np.zeros([1, 6])
        self.pdist = np.zeros([1, 6])
        self.tdist = np.zeros([1, 6])
        self.surface_dem = np.zeros([self.user['gridsize'], self.user['gridsize']], dtype=float)
        self.surface_ejc = np.zeros([self.user['gridsize'], self.user['gridsize']], dtype=float)
        self.ph1 = None
        
        if self.user['sfdcompare'] is not None:
            # Read sfdcompare file
            sfdfile = os.path.join(self.user['workingdir'], self.user['sfdcompare'])
            self.ph1 = util.read_formatted_ascii(sfdfile, skip_lines=0)
           

        # If this is a new simulation, run and post-process results. Otherwise, don't do anything more
        if isnew:
            # Starting new or old run?
            if (self.user['restart'].upper() == 'F'):
                print('Starting a new run')

                util.create_dir_structure(self.user, self.directories)
                # Delete any old output files
                for k, v in self.output_filenames.items():
                    if os.path.isfile(v):
                        os.remove(v)

                # Scale the production function to the simulation domain
                self.scale_production()

                # Setup Quasi-MC run

                if (self.user['quasimc'] == 'T'):

                    #Read list of real craters
                    print("quasi-MC mode is ON")
                    rclist = util.read_formatted_ascii(self.user['realcraterlist'], skip_lines = 0)
                    self.tempfile = os.path.join(currentdir, 'temp.in')

                    # Generate craterlist.dat
                    with open(self.user['ctemfile']) as perm, open(self.tempfile, "w") as temp:
                        for line in perm:
                            temp.write(line)
                    
                    #Write a temporary input file to generate the necessary quasimc files
                    self.permfile = self.user['ctemfile']
                    self.temp = util.write_temp_input(self.tempfile)
                    self.user['ctemfile'] = self.tempfile
                    self.user = util.read_user_input(self.user)
                    self.permin = os.path.join(currentdir, 'perm.in')
                    self.ctemin = os.path.join(currentdir, 'ctem.in')
                    os.rename(self.permfile, self.permin)
                    os.rename(self.tempfile, self.ctemin)
                    self.run()

                    os.replace(self.permin, self.ctemin)
                    self.user['ctemfile'] = self.permfile
                    self.user = util.read_user_input(self.user)

                    #Interpolate craterscale.dat to get impactor sizes from crater sizes given
                    df = pandas.read_csv(self.output_filenames['craterscale'], sep='\s+')
                    df['log(Dc)'] = np.log(df['Dcrat(m)'])
                    df['log(Di)'] = np.log(df['#Dimp(m)'])
                    xnew = df['log(Dc)'].values
                    ynew = df['log(Di)'].values
                    interp = interp1d(xnew, ynew, fill_value='extrapolate')
                    rclist[:,0] = np.exp(interp(np.log(rclist[:,0])))
    
                    #Convert age in Ga to "interval time"
                    rclist[:,5] = (self.user['interval'] * self.user['numintervals']) - craterproduction.Tscale(rclist[:,5], 'NPF_Moon')
                    rclist = rclist[rclist[:,5].argsort()]

                    #Export to dat file
                    util.write_realcraters(self.output_filenames['craterlist'], rclist)

                util.write_datfile(self.user, self.output_filenames['dat'], self.seedarr)
            else:
                print('Continuing a previous run')
                self.read_output()

        return
    
    def scale_production(self):
        """
        Scales the production function to the simulation domain and saves the scaled production function to a file that
        will be read in by the main Fortran program.
        """
        
        # Read production function file
        impfile = os.path.join(self.user['workingdir'], self.user['impfile'])
        prodfunction = util.read_formatted_ascii(impfile, skip_lines=0)

        # Create impactor production population
        area = (self.user['gridsize'] * self.user['pix']) ** 2
        self.production = np.copy(prodfunction)
        self.production[:, 1] = self.production[:, 1] * area * self.user['interval']

        # Write the scaled production function to file
        util.write_production(self.user, self.production)
        
        return
    
    def run(self):
        """
        Runs a complete simulation over all intervals specified in the input user. This method loops over all
        intervals and process outputs into images, and redirect output files to their apporpriate folders.
        
        This method replaces most of the functionality of the original ctem_driver.py
        """

        print('Beginning loops')
        while (self.user['ncount'] <= self.user['numintervals']):
            if (self.user['ncount'] > 0):
                # Move ctem.dat
                self.redirect_outputs(['dat'], 'misc')
                
                #Execute Fortran code
                self.compute_one_interval()
                
                # Read in output files
                self.read_output()

            # Process the output files
            self.process_output()

            # Update ncount
            self.user['ncount'] = self.user['ncount'] + 1

            if ((self.user['runtype'].upper() == 'STATISTICAL') or (self.user['ncount'] == 1)): # Reset the simulation
                self.user['restart'] = 'F'
                self.user['curyear'] = 0.0
                self.user['totalimpacts'] = 0
                self.user['masstot'] = 0.0

                # Delete tdistribution file, if it exists so that we don't accumulate true craters in statistical mode
                tdist_file = self.user['workingdir'] + 'tdistribution.dat'
                if os.path.isfile(tdist_file):
                    os.remove(tdist_file)

            else:
                self.user['restart'] = 'T'

            # Write ctem.dat file for next interval
            util.write_datfile(self.user, self.output_filenames['dat'], self.seedarr)

        return
    
    def compute_one_interval(self):
        """
        Executes the Fortran code to generate one interval of simulation output.
        """
        # Create crater population and display CTEM progress on screen
        print(self.user['ncount'], '  Calling FORTRAN routine')
        try:
            p = subprocess.Popen([os.path.join(self.user['workingdir'], 'CTEM')],
                              stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE,
                              universal_newlines=True)
            for line in p.stdout:
                print(line, end='')
            res = p.communicate()
            if p.returncode != 0:
                for line in res[1]:
                    print(line, end='')
                raise Exception ("CTEM Failure")
        except:
            print("Error executing main CTEM program")
            sys.exit()

        return
    
    def read_output(self):
        """
        Reads in all of the files generated by the Fortran code after one interval and redirects them to appropriate
        folders for storage after appending the interval number to the filename.
        """
        # Read Fortran output
        print(self.user['ncount'], '  Reading Fortran output')

        # Read surface dem(shaded relief) and ejecta data files
        self.surface_dem = util.read_unformatted_binary(self.output_filenames['dem'], self.user['gridsize'])
        self.surface_ejc = util.read_unformatted_binary(self.output_filenames['ejc'], self.user['gridsize'])

        # Read odistribution, tdistribution, and pdistribution files
        self.odist = util.read_formatted_ascii(self.output_filenames['odist'], skip_lines=1)
        self.tdist = util.read_formatted_ascii(self.output_filenames['tdist'], skip_lines=1)
        self.pdist = util.read_formatted_ascii(self.output_filenames['pdist'], skip_lines=1)

        # Read impact mass from file
        self.impact_mass = util.read_impact_mass(self.output_filenames['impmass'])

        # Read ctem.dat file
        util.read_datfile(self.user, self.output_filenames['dat'], self.seedarr)

        
    def process_output(self):
        """
        Processes output to update masses, time, computes regolith depth, generates all plots, and redirects files
        into intermediate storage.
        """
        # Display results
        print(self.user['ncount'], '  Generating surface images and plots')

        # Write surface dem, surface ejecta and shaded relief data
        util.image_dem(self.user, self.surface_dem)
        if (self.user['saverego'].upper() == 'T'):
            util.image_regolith(self.user, self.surface_ejc)
        if (self.user['saveshaded'].upper() == 'T'):
            util.image_shaded_relief(self.user, self.surface_dem)
        
        if self.user['ncount'] > 0: # These aren't available yet from the initial conditions
            
            # Save copy of crater distribution files
            # Update user: mass, curyear, regolith properties
            self.user['masstot'] = self.user['masstot'] + self.impact_mass
    
            self.user['curyear'] = self.user['curyear'] + self.user['fracdone'] * self.user['interval']
            template = "%(fracdone)9.6f %(curyear)19.12E\n"
            with open(self.output_filenames['fracdone'], 'w') as fp_frac:
                fp_frac.write(template % self.user)
    
            reg_text = "%19.12E %19.12E %19.12E %19.12E\n" % (self.user['curyear'],
                                                              np.mean(self.surface_ejc), np.amax(self.surface_ejc),
                                                              np.amin(self.surface_ejc))
            with open(self.output_filenames['regodepth'], 'w') as fp_reg:
                fp_reg.write(reg_text)
            # Redirect output files to storage
            self.redirect_outputs(['odist', 'ocum', 'pdist', 'tdist'], 'dist')
            if (self.user['savetruelist'].upper() == 'T'):
                self.redirect_outputs(['tcum'], 'dist')
            self.redirect_outputs(['impmass'], 'misc')
            


    def redirect_outputs(self, filekeys, foldername):
        """
        Copies a set of output files from the working directory into a subfolder.
        Takes as input the dictionaries of user parameters and output file names, the dictionary keys to the file names
        you wish to redirect, and the redirection destination folder name. The new name will be the key name + zero padded
        interval number.

        Example:
            calling redirect_outputs(['odist','tdist'], 'dist') when user['ncount'] is 1
            should do the following:
            copy 'odistribution.dat' to 'dist/odist_000001.dat'
            copy 'tdistribution.dat' to 'dist/tdist_000001.dat'
        """
        
        for k in filekeys:
            forig = self.output_filenames[k]
            fdest = os.path.join(self.user['workingdir'], foldername, f"{k}_{self.user['ncount']:06d}.dat")
            shutil.copy2(forig, fdest)
            
    def cleanup(self):
        """
        Deletes all files and folders generated by CTEM.
        """
        # This is a list of files generated by the main Fortran program
        print("Deleting all files generated by CTEM")
        util.destroy_dir_structure(self.user, self.directories)
        for key, filename in self.output_filenames.items():
            print(f"Deleting file {filename}")
            try:
                os.remove(filename)
            except OSError as error:
                print(error)
        # Delete scaled production file
        prodfile = self.user['sfdfile']
        print(f"Deleting file {prodfile}")
        try:
            os.remove(prodfile)
        except OSError as error:
            print(error)

        return

if __name__ == '__main__':
    sim = Simulation()
    sim.run()