import numpy as np
import os
import shutil
from matplotlib.colors import LightSource
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import re
from tempfile import mkstemp
from scipy.io import FortranFile

# Set pixel scaling common for image writing, at 1 pixel/ array element
dpi = 72.0

# These are directories that are created by CTEM in order to store intermediate results

def create_dir_structure(user, directories):
    """
    Create directories for various output files if they do not already exist
    """

    for dirname in directories:
        dirpath = os.path.join(user['workingdir'], dirname)
        if not os.path.isdir(dirpath):
            print(f"Creating directory {dirpath}")
            os.makedirs(dirpath)
    
    return

def destroy_dir_structure(user, directories):
    """
    Deletes directories generated by create_dir_structure
    """
    for dirname in directories:
        dirpath = os.path.join(user['workingdir'], dirname)
        if os.path.isdir(dirpath):
            print(f"Deleting directory {dirpath}")
            shutil.rmtree(dirpath, ignore_errors=True)

    return

def image_dem(user, DEM):
    dpi = 300.0  # 72.0
    pix = user['pix']
    gridsize = user['gridsize']
    ve = 1.0
    azimuth = 300.0  # user['azimuth']
    solar_angle = 20.0  # user['solar_angle']
    
    ls = LightSource(azdeg=azimuth, altdeg=solar_angle)
    dem_img = ls.hillshade(np.flip(DEM, axis=0), vert_exag=ve, dx=pix, dy=pix)
    
    # Generate image to put into an array
    height = gridsize / dpi
    width = gridsize / dpi
    fig = plt.figure(figsize=(width, height), dpi=dpi)
    ax = plt.axes([0, 0, 1, 1])
    ax.imshow(dem_img, interpolation="nearest", cmap='gray', vmin=0.0, vmax=1.0)
    plt.axis('off')
    # Save image to file
    filename = os.path.join(user['workingdir'],'surf',"surf%06d.png" % user['ncount'])
    plt.savefig(filename, dpi=dpi, bbox_inches=0)
    
    return


def image_regolith(user, regolith):
    # Create scaled regolith image
    minref = user['pix'] * 1.0e-4
    maxreg = np.amax(regolith)
    minreg = np.amin(regolith)
    if (minreg < minref): minreg = minref
    if (maxreg < minref): maxreg = (minref + 1.0e3)
    regolith_scaled = np.copy(regolith)
    np.place(regolith_scaled, regolith_scaled < minref, minref)
    regolith_scaled = 254.0 * (
            (np.log(regolith_scaled) - np.log(minreg)) / (np.log(maxreg) - np.log(minreg)))
    
    # Save image to file
    filename = os.path.join(user['workingdir'],'rego', "rego%06d.png" % user['ncount'])
    height = user['gridsize'] / dpi
    width = height
    fig = plt.figure(figsize=(width, height), dpi=dpi)
    fig.figimage(regolith_scaled, cmap=cm.cividis, origin='lower')
    plt.savefig(filename)
    
    return


def image_shaded_relief(user, DEM):
    dpi = 300.0  # 72.0
    pix = user['pix']
    gridsize = user['gridsize']
    ve = 1.0
    mode = 'overlay'
    azimuth = 300.0  # user['azimuth']
    solar_angle = 20.0  # user['solar_angle']
    
    ls = LightSource(azdeg=azimuth, altdeg=solar_angle)
    cmap = cm.cividis
    
    # If min and max appear to be reversed, then fix them
    if (user['shadedminh'] > user['shadedmaxh']):
        temp = user['shadedminh']
        user['shadedminh'] = user['shadedmaxh']
        user['shadedmaxh'] = temp
    else:
        user['shadedminh'] = user['shadedminh']
        user['shadedmaxh'] = user['shadedmaxh']
    
    # If no shadedmin/max user are read in from ctem.dat, determine the values from the data
    if (user['shadedminhdefault'] == 1):
        shadedminh = np.amin(DEM)
    else:
        shadedminh = user['shadedminh']
    if (user['shadedmaxhdefault'] == 1):
        shadedmaxh = np.amax(DEM)
    else:
        shadedmaxh = user['shadedmaxh']
    
    dem_img = ls.shade(np.flip(DEM, axis=0), cmap=cmap, blend_mode=mode, fraction=1.0,
                       vert_exag=ve, dx=pix, dy=pix,
                       vmin=shadedminh, vmax=shadedmaxh)
    
    # Generate image to put into an array
    height = gridsize / dpi
    width = gridsize / dpi
    fig = plt.figure(figsize=(width, height), dpi=dpi)
    ax = plt.axes([0, 0, 1, 1])
    ax.imshow(dem_img, interpolation="nearest", vmin=0.0, vmax=1.0)
    plt.axis('off')
    # Save image to file
    filename = os.path.join(user['workingdir'],'shaded',"shaded%06d.png" % user['ncount'])
    plt.savefig(filename, dpi=dpi, bbox_inches=0)
    return user


def read_datfile(user, datfile, seedarr):
    # Read and parse ctem.dat file
    
    # Read ctem.dat file
    print('Reading input file ' + datfile)
    fp = open(datfile, 'r')
    lines = fp.readlines()
    fp.close()
    
    # Parse file lines and update parameter fields
    fields = lines[0].split()
    if len(fields) > 0:
        user['totalimpacts'] = real2float(fields[0])
        user['ncount'] = int(fields[1])
        user['curyear'] = real2float(fields[2])
        user['restart'] = fields[3]
        user['fracdone'] = real2float(fields[4])
        user['masstot'] = real2float(fields[5])
    
    # Parse remainder of file to build seed array
    nlines = len(lines)
    index = 1
    while (index < nlines):
        fields = lines[index].split()
        seedarr[index - 1] = real2float(fields[0])
        index += 1
    
    user['seedn'] = index - 1
    
    return


def read_formatted_ascii(filename, skip_lines):
    # Generalized ascii text reader
    # For use with sfdcompare, production, odist, tdist, pdist data files
    try:
        data = np.genfromtxt(filename, skip_header=skip_lines)
    except:
        print(f"Error reading {filename}")
        data = None
    return data


def read_impact_mass(filename):
    # Read impact mass file
    
    fp = open(filename, 'r')
    line = fp.readlines()
    fp.close()
    
    fields = line[0].split()
    if (len(fields) > 0):
        mass = real2float(fields[0])
    else:
        mass = 0
    
    return mass


# Write production function to file production.dat
# This file format does not exactly match that generated from IDL. Does it work?
def read_user_input(user):
    # Read and parse ctem.in file
    inputfile = user['ctemfile']
    
    # Read ctem.in file
    print('Reading input file ' + user['ctemfile'])
    with open(inputfile, 'r') as fp:
        lines = fp.readlines()
    
    # Process file text
    for line in lines:
        fields = line.split()
        if len(fields) > 0:
            if ('pix' == fields[0].lower()): user['pix'] = real2float(fields[1])
            if ('gridsize' == fields[0].lower()): user['gridsize'] = int(fields[1])
            if ('seed' == fields[0].lower()): user['seed'] = int(fields[1])
            if ('sfdfile' == fields[0].lower()): user['sfdfile'] = os.path.join(user['workingdir'],fields[1])
            if ('impfile' == fields[0].lower()): user['impfile'] = os.path.join(user['workingdir'],fields[1])
            if ('maxcrat' == fields[0].lower()): user['maxcrat'] = real2float(fields[1])
            if ('sfdcompare' == fields[0].lower()): user['sfdcompare'] = os.path.join(user['workingdir'], fields[1])
            if ('realcraterlist' == fields[0].lower()): user['realcraterlist'] = os.path.join(user['workingdir'], fields[1])
            if ('interval' == fields[0].lower()): user['interval'] = real2float(fields[1])
            if ('numintervals' == fields[0].lower()): user['numintervals'] = int(fields[1])
            if ('popupconsole' == fields[0].lower()): user['popupconsole'] = fields[1]
            if ('saveshaded' == fields[0].lower()): user['saveshaded'] = fields[1]
            if ('saverego' == fields[0].lower()): user['saverego'] = fields[1]
            if ('savepres' == fields[0].lower()): user['savepres'] = fields[1]
            if ('savetruelist' == fields[0].lower()): user['savetruelist'] = fields[1]
            if ('runtype' == fields[0].lower()): user['runtype'] = fields[1]
            if ('restart' == fields[0].lower()): user['restart'] = fields[1]
            if ('quasimc' == fields[0].lower()): user['quasimc'] = fields[1]
            if ('shadedminh' == fields[0].lower()):
                user['shadedminh'] = real2float(fields[1])
                user['shadedminhdefault'] = 0
            if ('shadedmaxh' == fields[0].lower()):
                user['shadedmaxh'] = real2float(fields[1])
                user['shadedmaxhdefault'] = 0
    
    # Test values for further processing
    if (user['interval'] <= 0.0):
        print('Invalid value for or missing variable INTERVAL in ' + inputfile)
    if (user['numintervals'] <= 0):
        print('Invalid value for or missing variable NUMINTERVALS in ' + inputfile)
    if (user['pix'] <= 0.0):
        print('Invalid value for or missing variable PIX in ' + inputfile)
    if (user['gridsize'] <= 0):
        print('Invalid value for or missing variable GRIDSIZE in ' + inputfile)
    if (user['seed'] == 0):
        print('Invalid value for or missing variable SEED in ' + inputfile)
    if (user['impfile'] is None):
        print('Invalid value for or missing variable IMPFILE in ' + inputfile)
    if (user['popupconsole'] is None):
        print('Invalid value for or missing variable POPUPCONSOLE in ' + inputfile)
    if (user['saveshaded'] is None):
        print('Invalid value for or missing variable SAVESHADED in ' + inputfile)
    if (user['saverego'] is None):
        print('Invalid value for or missing variable SAVEREGO in ' + inputfile)
    if (user['savepres'] is None):
        print('Invalid value for or missing variable SAVEPRES in ' + inputfile)
    if (user['savetruelist'] is None):
        print('Invalid value for or missing variable SAVETRUELIST in ' + inputfile)
    if (user['runtype'] is None):
        print('Invalid value for or missing variable RUNTYPE in ' + inputfile)
    if (user['restart'] is None):
        print('Invalid value for or missing variable RESTART in ' + inputfile)
    
    return user


def read_unformatted_binary(filename, gridsize, kind='DP'):
    # Read unformatted binary files created by Fortran
    # For use with surface ejecta and surface dem data files
    if kind == 'DP':
        dt = np.dtype('f8')
    elif kind == 'SP':
        dt = np.dtype('f4')
    elif kind == 'I4B':
        dt = np.dtype('<i4')
    elif kind == 'I8B':
        dt = np.dtypye('<i8')
    data = np.fromfile(filename, dtype=dt)
    data.shape = (gridsize, gridsize)
    
    return data


def read_linked_list_binary(filename, gridsize):
    data = np.empty((gridsize,gridsize),dtype="object")
    with FortranFile(filename, 'r') as f:
        for i in np.arange(gridsize):
            for j in np.arange(gridsize):
                data[j, i] = f.read_reals(np.float64)
    return data


def real2float(realstr):
    """
    Converts a Fortran-generated ASCII string of a real value into a np float type. Handles cases where double precision
    numbers in exponential notation use 'd' or 'D' instead of 'e' or 'E'

    Parameters
    ----------
    realstr : string
        Fortran-generated ASCII string of a real value.

    Returns
    -------
     : float
        The converted floating point value of the input string
    """
    return float(realstr.replace('d', 'E').replace('D', 'E'))

def sed(pattern, replace, source, count=0):
    """Python implementation of unix sed command; not fully functional sed."""

    fin = open(source, 'r')
    num_replaced = 0

    fd, name = mkstemp()
    fout = open(name, 'w')

    for line in fin:
        out = re.sub(pattern, replace, line)
        fout.write(out)

        if out != line:
            num_replaced += 1
        if count and num_replaced > count:
            break

    fout.writelines(fin.readlines())


    fin.close()
    fout.close()

    shutil.move(name, source)
    
    return

def write_datfile(user, filename, seedarr):
    # Write various user and random number seeds into ctem.dat file
    fp = open(filename, 'w')
    
    template = "%(totalimpacts)17d %(ncount)12d %(curyear)19.12E %(restart)s %(fracdone)9.6f %(masstot)19.12E\n"
    fp.write(template % user)
    
    # Write random number seeds to the file
    for index in range(user['seedn']):
        fp.write("%12d\n" % seedarr[index])
    
    fp.close()
    
    return


def write_production(filename, production):
    np.savetxt(filename, production, fmt='%1.8e', delimiter='   ')
    
    return


def write_realcraters(filename, realcraters):
    """Writes file of real craters for use in quasi-MC runs"""

    np.savetxt(filename, realcraters, fmt='%1.8e', delimiter='\t')

    return

def write_temp_input(filename):
    """Makes changes to a temporary input file for use when generating craterlist.dat for quasimc runs"""

    sed('testflag', 'testflag T!', filename)
    sed('testimp', 'testimp 10 !', filename)
    sed('quasimc', 'quasimc F!', filename)
    sed('interval', 'interval 1 !', filename)
    sed('numinterval 1 !s', 'numintervals 1 !', filename)

    return